name: Github Pages Astro CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
      - uses: actions/checkout@v2
      
      # If we need a particular version of node for Astro :
      # - name: Setup Node
      #     uses: actions/setup-node@v1
      #     with:
      #       node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          touch ./dist/.nojekyll

      - name: Deploy to gh-pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist
